insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'remover', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'remover', '20 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'hervir', '45 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'remover', 'media hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'remover', '20 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'hervir', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'remover', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'freir', '20 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'calentar a fuego lento', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'remover', '20 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'remover', 'mas de una hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'hervir', 'mas de una hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'freir', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'hervir', '20 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'calentar a fuego lento', 'mas de una hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'hervir', 'media hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'calentar a fuego lento', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'freir', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'freir', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'hervir', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'remover', '45 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', '20 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'calentar a fuego lento', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'freir', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'freir', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'remover', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'hervir', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'hervir', '20 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'calentar a fuego lento', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'freir', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'calentar a fuego lento', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'freir', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'freir', 'menos de una hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'remover', '45 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'remover', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'freir', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'calentar a fuego lento', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'calentar a fuego lento', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'calentar a fuego lento', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'remover', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'hervir', 'media hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'calentar a fuego lento', '20 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'remover', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'freir', 'media hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'hervir', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'calentar a fuego lento', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'freir', 'media hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'hervir', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'calentar a fuego lento', 'media hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'hervir', '45 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'hervir', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'hervir', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'hervir', '20 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'freir', 'menos de una hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'hervir', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'calentar a fuego lento', 'media hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'hervir', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'calentar a fuego lento', '20 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'hervir', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'calentar a fuego lento', 'media hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'calentar a fuego lento', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'calentar a fuego lento', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'remover', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'remover', 'menos de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'hervir', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'hervir', 'media hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'freir', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'calentar a fuego lento', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'calentar a fuego lento', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'freir', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'freir', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'hervir', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'hervir', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'calentar a fuego lento', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'calentar a fuego lento', 'media hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'calentar a fuego lento', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'remover', 'media hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'calentar a fuego lento', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'calentar a fuego lento', 'media hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'hervir', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'remover', '45 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'hervir', 'media hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'remover', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'hervir', 'mas de una hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'remover', 'menos de una hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'remover', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'calentar a fuego lento', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'calentar a fuego lento', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'freir', '45 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'remover', 'menos de una hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'hervir', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'freir', '20 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'hervir', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'hervir', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'remover', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'freir', '20 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'hervir', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'calentar a fuego lento', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'hervir', '45 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'calentar a fuego lento', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'freir', '20 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'hervir', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'freir', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'calentar a fuego lento', 'menos de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'freir', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'hervir', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'remover', '20 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'calentar a fuego lento', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', 'media hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'hervir', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'hervir', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'calentar a fuego lento', 'menos de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'remover', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'calentar a fuego lento', 'media hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'calentar a fuego lento', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'remover', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'remover', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'remover', '20 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'freir', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'calentar a fuego lento', '20 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'calentar a fuego lento', '45 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'calentar a fuego lento', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', 'menos de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'hervir', 'menos de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'freir', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('lentejas', 'hervir', 'menos de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'remover', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('atun', 'remover', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'remover', 'menos de una hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'remover', 'media hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'freir', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'remover', '45 minutos', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'hervir', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'remover', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('guisantes', 'hervir', 'media hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'calentar a fuego lento', '20 minutos', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'calentar a fuego lento', 'mas de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'calentar a fuego lento', 'menos de una hora', 'DULCES');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('azucar', 'hervir', 'media hora', 'PASTAS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('queso', 'calentar a fuego lento', 'menos de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('huevos', 'calentar a fuego lento', 'mas de una hora', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('macarrones', 'hervir', '20 minutos', 'OTROS');
insert into Receta (ingredientes, preparacion, tiempoCocinar, recetaCategoria) values ('pollo', 'remover', 'menos de una hora', 'DULCES');
